### ISSUE TITLE
It's a bit awkward to submit pull requests

### ISSUE THREAD

**Issue by alexjj** [aumayr/beancount-sql-queries#1]
I really like the idea of this site, and sharing and seeing other's queries from the mailing list has helped me.

I tried to do a pull request but using the github built in site generator to make this site doesn't lend itself to making pull requests easily. I have to regenerate the site and it changes various things in addition to the content.

I can paste what I was going to add below but maybe you want to use a static site generator (jekyll or 9000 other ones) that autobuild on github pages, so people just edit a markdown file etc. to add their query? I know it's more work for you but would make it simpler to contribute, in my opinion.

**Comment by aumayr** [comment]
Excellent idea! I was waiting for some feedback on this site/idea, and you are the first one to really come forward :-)

I'll convert it to Jekyll, so it will be built using Github Pages.

**Comment by aumayr** [comment]
@alexjj I converted everything to a Jekyll-powered page.
