### ISSUE TITLE
Is it possible to combine the "balance" column with aggregate functions?

### ISSUE THREAD

**Issue by jokorn** [aumayr/beancount-sql-queries#13]
I have tried to create a beancount-query to show the increase in net worth per month and the total net worth in one query. But it doesn't seem like I can combine the sum function with the balance function:

 SELECT year(date) as year, month, sum(value(position)) as NetIncrease, balance as NetWorth
 WHERE account ~ 'Assets|Liabilities'
 AND not account ~ 'Pension'
 GROUP BY year, month
 ORDER by year, month

This returns:

> "_All non-aggregates must be covered by GROUP-BY clause in aggregate query_". 

However, if I instead add:

GROUP BY year, month, NetWorth 

Then the Fava website returns:

> "_The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application._"

Is it possible to combine sum and balance to produce the result I want?

**Comment by aumayr** [comment]
This sounds like a bug in Beancount. Can you post this as an issue in the Beancount repository (https://bitbucket.org/blais/beancount/issues/new) and on the Beancount mailing list (https://groups.google.com/forum/#!forum/beancount)? @blais might be able to help you here.

This is the query I tried:

```javascript
SELECT year(date) as year, month, sum(value(position)) as NetIncrease, balance as NetWorth
WHERE account ~ 'Assets|Liabilities'
AND not account ~ 'Pension'
GROUP BY year, month, NetWorth
ORDER by year, month
```

This is the stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'QueryShell' object has no attribute 'do_SELECT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dominik/Projects/beancount/beancount/src/python/beancount/query/shell.py", line 258, in run_parser
    self.dispatch(statement)
  File "/Users/dominik/Projects/beancount/beancount/src/python/beancount/query/shell.py", line 238, in dispatch
    return method(statement)
  File "/Users/dominik/Projects/beancount/fava/fava/core/query_shell.py", line 83, in on_Select
    self.options_map)
  File "/Users/dominik/Projects/beancount/beancount/src/python/beancount/query/query_execute.py", line 288, in execute_query
    store = agg_store[row_key]
TypeError: unhashable type: 'Inventory'
```

**Comment by jokorn** [comment]
Thank you. I'll try posting in the Beancount repository. I do not have a login for the google group so I'll wait a bit before posting in the beancount mailing list.
