### ISSUE TITLE
Queries to add:

### ISSUE THREAD

**Issue by alexjj** [aumayr/beancount-sql-queries#2]
### Expenses, Income and Loans/Mortgage monthly totals

This query produces a table showing top level account monthly totals. A very high level summary over all time. FLATTEN puts each currency on its own line. Useful for saving as csv/pasting into a spreadsheet.

``` sql
SELECT 
        year, month, root(account, 1) as ar, sum(position) as pos
      FROM 
        date > 2010-01-01 AND date < 2016-12-31
      WHERE 
         account ~ "Expenses" OR
         account ~ "Liabilities:Mortgage" OR
         account ~ "Liabilities:Loan" OR
         account ~ "Income"
      GROUP BY year, month, ar 
      ORDER BY year, month, ar 
      FLATTEN
```
### Monthly expenses report

Similar to the above query but now showing all expense subaccounts

``` sql
SELECT 
        year, month, account, sum(position) 
    FROM
        date > 2015-01-01 AND date < 2016-02-29
    WHERE 
        account ~ "Expenses"
        GROUP BY year, month, account 
        ORDER by year, month, account
        FLATTEN
```

**Comment by aumayr** [comment]
@alexjj Thanks for the queries! I already incorporated them into the site. 

Posts (queries) have the feature of displaying the author's name and email address - I did not display yours, but commented them out (see 1f21d78ac1414ff63f95ee8cd04dda83e415ac42). 

Do you want them to be shown on the page?
